FROM prom/mysqld-exporter:latest

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_DATABASE=$MYSQL_DATABASE

COPY .my.cnf /.my.cnf

EXPOSE 9104